service: schedule-events-dynamodb-aws

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region : us-west-1
  memorySize: 512
  timeout : 10
  environment: ${file(./serverless_ssm.yml)}
  apiGateway:
    apiKeys:
      - name : xApiKey
        value : ${file(./serverless_ssm.yml):X_API_KEY}

plugins:
    - serverless-dynamodb-local
    - serverless-offline-ssm
    - serverless-offline  

functions:
  createUser:
    handler: src/lambdas/createUser.add
    events:
      - http:
          method: post
          path: create
          private: true        
  getAllUsers:
    handler: src/lambdas/getUsers.get
    events:
      - http:
          method: get
          path: get-all
          private: true


resources:
  - ${file(src/resources/api-gateway.yml)}
  - ${file(src/resources/dynamo-table.yml)}    

custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002    
  serverless-offline-ssm:
    stages:
      - dev
    ssm: 
      ${file(./serverless_ssm.yml)}
  dynamodb:
    stages:
      - dev
      
